nguyet-nguyen/PractiseFE

src/App.js
src/layouts/pages/landing-pages/sign-in/index.js
src/pages/Admin/Header/sections/UserMenu.js
src/pages/Admin/SignIn/index.js
src/pages/LandingPages/SignIn/index.js

design sign in form user ui

---

src/layouts/pages/authentication/sign-in/index.js
src/layouts/pages/authentication/sign-up/index.js
src/layouts/pages/landing-pages/sign-in/index.js
src/pages/LandingPages/SignIn/index.js
src/pages/LandingPages/SignUp/index.js
src/routes.js

design sign up form user ui

---

src/pages/LandingPages/UserProfile/index.js
src/pages/LandingPages/UserProfile/sections/Breadcrumbs.js
src/pages/LandingPages/UserProfile/sections/Profile.js
src/routes.js

design user profile

---

src/address.js
src/pages/Admin/SignUp/index.js
src/pages/Admin/Users/sections/UserTable.js
src/pages/LandingPages/SignIn/index.js
src/pages/LandingPages/SignUp/index.js

commit fix form data

---

src/pages/LandingPages/UserProfile/sections/Profile.js

form update user info ui

---

src/features/Api.js
src/pages/LandingPages/UserProfile/sections/Profile.js

api get user info

---

src/features/Api.js
src/pages/LandingPages/UserProfile/sections/ModalUpdateAvatar.js
src/pages/LandingPages/UserProfile/sections/ModalUpdateUser.js
src/pages/LandingPages/UserProfile/sections/Profile.js

50 call api change user profile avatar

---

src/assets/css/main.css
src/pages/CustomPopupMess/index.js
src/pages/LandingPages/UserProfile/sections/ModalUpdateAvatar.js

52 custom popup message

---

src/features/Api.js
src/pages/LandingPages/SignIn/index.js
src/pages/LandingPages/SignUp/index.js

56 using onblur to validate email field

---

src/assets/css/main.css
src/features/Api.js
src/pages/LandingPages/ProductDetail/sections/ItemDetail.js
src/pages/LandingPages/UserProfile/sections/Profile.js

62 add to cart function

---

src/features/Api.js
src/pages/LandingPages/ShoppingCart/sections/Cart.js

65 get all carts from user shopping cart

---

src/features/Api.js
src/pages/LandingPages/ShoppingCart/sections/Cart.js

68 remove item from shopping cart

---

src/App.js
src/examples/Navbars/DefaultNavbar/index.js
src/features/Api.js
src/pages/CustomPopupMess/index.js
src/pages/LandingPages/ProductDetail/sections/BreadcrumbsItemDetail.js
src/pages/LandingPages/ProductDetail/sections/ItemDetail.js
src/pages/LandingPages/ShoppingCart/sections/Cart.js
src/pages/LandingPages/SignUp/index.js
src/pages/LandingPages/UserProfile/sections/ModalUpdateAvatar.js
src/pages/LandingPages/UserProfile/sections/Profile.js
src/routes.js

67 update quantity total in shopping cart

---

src/pages/LandingPages/ShoppingCart/sections/Cart.js
src/pages/LandingPages/UserProfile/sections/Profile.js

12 user order list UI

---

src/features/Api.js
src/pages/LandingPages/UserProfile/sections/Profile.js

49 call api get user order list

---

src/App.js
src/features/Api.js
src/pages/LandingPages/OrderDetail/index.js
src/pages/LandingPages/OrderDetail/sections/Breadcrumbs.js
src/pages/LandingPages/OrderDetail/sections/OrdDetail.js
src/pages/LandingPages/UserProfile/sections/Profile.js

82 view user order detail function

---

src/App.js
src/features/Api.js
src/pages/Admin/OrderListAdmin/sections/OrderDetail.js
src/pages/Admin/OrderListAdmin/sections/OrderList.table.js
src/pages/Admin/Products/sections/ProductsTable.js

87 apply view order detail function to admin page

---

src/features/Api.js
src/pages/Admin/OrderListAdmin/sections/OrderList.table.js
src/pages/LandingPages/ShoppingCart/sections/Cart.js
src/pages/LandingPages/UserProfile/sections/Profile.js

91 update status order for admin and user page

---

src/pages/LandingPages/Checkout/sections/CheckoutForm.js
src/pages/LandingPages/ShoppingCart/sections/Cart.js
yarn.lock

97 checkout success message

---

src/features/Api.js
src/pages/LandingPages/ShoppingCart/sections/Cart.js
src/pages/LandingPages/UserProfile/sections/Profile.js

99 buy again function

---

src/examples/Footers/DefaultFooter/index.js

change footer ui

---

src/features/Api.js
src/pages/LandingPages/Checkout/sections/CheckoutForm.js
src/pages/LandingPages/Home/sections/Banner.js
src/pages/LandingPages/ShoppingCart/sections/Cart.js

122 payment method paypal

---

src/pages/LandingPages/OrderDetail/sections/OrdDetail.js
src/pages/LandingPages/UserProfile/sections/Profile.js

set paid and unpaid

---

src/assets/css/main.css
src/pages/Admin/OrderListAdmin/sections/OrderList.table.js
src/pages/LandingPages/Checkout/sections/CheckoutForm.js

128 set paid or unpaid for admin orders

---

src/address.js

extra info on address file

---

src/pages/Admin/Products/sections/AddProductForm.js
src/pages/Admin/Products/sections/ProductsTable.js
src/pages/Admin/Products/sections/UpdateProductForm.js
src/pages/Admin/SignUp/sections/SignUpForm.js

138 breadcrumbs in admins page

---

src/App.js
src/pages/Admin/Products/sections/AddProductForm.js
src/pages/Admin/Products/sections/UpdateProductForm.js
src/pages/Admin/Sidebar/index.js
src/pages/Admin/SignIn/index.js
src/pages/LandingPages/Checkout/sections/CheckoutForm.js
src/pages/LandingPages/Home/sections/Category.js
src/pages/LandingPages/Home/sections/HotDeal.js
src/pages/LandingPages/Home/sections/ProductList.js
src/pages/LandingPages/ProductDetail/sections/BreadcrumbsItemDetail.js
src/pages/NotFound/index.js

141 not found page

---

public/index.html
src/pages/Admin/OrderListAdmin/sections/OrderDetail.js
src/pages/Admin/Products/sections/AddProductForm.js
src/pages/Admin/Products/sections/ProductsTable.js
src/pages/Admin/Products/sections/UpdateProductForm.js
src/pages/Admin/SignUp/sections/SignUpForm.js
src/pages/LandingPages/AboutUs/sections/IntroLogoName.js
src/pages/LandingPages/Checkout/sections/CheckoutForm.js
src/pages/LandingPages/Home/function/CardProduct.js
src/pages/LandingPages/Home/sections/ProductList.js
src/pages/LandingPages/OrderDetail/sections/OrdDetail.js
src/pages/LandingPages/ProductDetail/sections/ItemDetail.js
src/pages/LandingPages/ProductListPage/sections/Breadcrumbs.js
src/pages/LandingPages/ProductListPage/sections/SideNavFilter.js
src/pages/LandingPages/ShoppingCart/sections/Cart.js
src/pages/LandingPages/SignUp/index.js
src/pages/LandingPages/UserProfile/sections/Profile.js

143 fix error on console

---

public/index.html
src/pages/Admin/Products/sections/AddProductForm.js
src/pages/Admin/Products/sections/UpdateProductForm.js

set description required
